site_visiting:
    resource: "@SiteVisitingBundle/Resources/config/routing.yml"
    prefix:   /

store_news:
    resource: "@StoreNewsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
