Store\NewsBundle\Entity\News:
    type: entity
    table: news
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
        title:
            type: string
            length: 255
        content:
            type: text
    manyToOne:
        kategoria:
            targetEntity: Kategoria
            inversedBy: newss
            joinColumn:
                name: kategoria_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
